language: python
sudo: true
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
  - sudo apt-get install python-m2crypto
  - sudo apt-get install python-lxml
install:
  - pip install --no-deps -r requirements/test.txt --use-mirrors
script: ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
