language: python
python:
 - "2.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install swig

install:
  - pip install --no-deps -r requirements/test.txt --use-mirrors
  - cp solitude/settings/local.py{-dist,}
  - mysqladmin create playdoh_app
script: ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_succes: change
    on_failure: always