language: python
python:
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install swig
  - sudo apt-get install python-m2crypto

install:
  - pip install --no-deps -r requirements/test.txt --use-mirrors
  - cp webpay/settings/local.py{-dist,}
  - mysqladmin create zamboni
script: ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
